-- creation tables
create table locality_types (
    locality_type_id int generated by default as identity primary key,
    locality_type_name varchar(127) not null
);
create table locality_trip_descriptions (
    locality_trip_description_id int generated by default as identity primary key,
    description text not null,
    count_of_landmarks int,
    count_of_hotels int,
    year_of_foundation int
);
create table localities (
    locality_id int generated by default as identity primary key,
    locality_name varchar(127) not null unique,
    population int not null,
    area float not null,
    locality_type_id int references locality_types(locality_type_id),
    locality_trip_description_id int references locality_trip_descriptions(locality_trip_description_id)
);
create table road_types (
    road_type_id int generated by default as identity primary key,
    road_type_name varchar(127) not null
);
create table roads (
    f_locality_id int references localities(locality_id),
    s_locality_id int references localities(locality_id),
    length int not null,
    road_type_id int references road_types(road_type_id)
);
-- fill tables with data
INSERT INTO locality_types(locality_type_name)
VALUES ('City'),
    ('Village');
INSERT INTO locality_trip_descriptions(
        description,
        count_of_landmarks,
        count_of_hotels,
        year_of_foundation
    )
VALUES (
        'Omsk is the third largest city in Siberia after Novosibirsk and Krasnoyarsk, and the twelfth-largest city in Russia. It is an important transport node, serving as a train station for the Trans-Siberian Railway and as a staging post for the Irtysh River.',
        17,
        20,
        1716
    ),
    (
        'Novosibirsk is the largest city and administrative centre of Novosibirsk Oblast and the Siberian Federal District in Russia. As of the 2021 Census, it had a population of 1,633,595, making it the most populous city in Siberia and the third-most populous city in Russia after Moscow and Saint Petersburg. The city is located in southwestern Siberia, on the banks of the Ob River.',
        87,
        94,
        1893
    ),
    (
        'Yekaterinburg is a city and the administrative centre of Sverdlovsk Oblast and the Ural Federal District, Russia. The city is located on the Iset River between the Volga-Ural region and Siberia, with a population of roughly 1.5 million residents, up to 2.2 million residents in the urban agglomeration. Yekaterinburg is the fourth-largest city in Russia, the largest city in the Ural Federal District, and one of Russias main cultural and industrial centres. Yekaterinburg has been dubbed the Third capital of Russia, as it is ranked third by the size of its economy, culture, transportation and tourism.',
        801,
        125,
        1723
    );
INSERT INTO localities(
        locality_name,
        population,
        area,
        locality_type_id,
        locality_trip_description_id
    )
VALUES -- id: 1
    ('Omsk', 1181000, 572.5, 1, 1),
    -- id: 2
    ('Sosnovskoe', 3000, 20.7, 2, null),
    -- id: 3
    ('Kokshetau', 161000, 233.6, 1, null),
    -- id: 4
    ('Tyumen', 581000, 698.5, 1, null),
    -- id: 5
    ('Chelyabinsk', 1202000, 530, 1, null),
    -- id: 6
    ('Yekaterinburg', 1495000, 1111, 1, 3),
    -- id: 7
    ('Novosibirsk', 1453000, 502.7, 1, 2),
    -- id: 8
    ('Kemerovo', 531000, 294.8, 1, null),
    -- id: 9
    ('Barnaul', 612000, 320.1, 1, null),
    -- id: 10
    ('Novokuznetsk', 547000, 424.3, 1, null),
    -- id: 11
    ('Tomsk', 524000, 294.6, 1, null);
INSERT INTO road_types(road_type_name)
VALUES ('Highway');
INSERT INTO roads(
        f_locality_id,
        s_locality_id,
        length,
        road_type_id
    )
VALUES(1, 7, 639, 1),
    (7, 8, 270, 1),
    (2, 1, 1, 1),
    (2, 3, 3, 1),
    (2, 4, 4, 1),
    (2, 5, 5, 1),
    (2, 6, 6, 1),
    (2, 7, 7, 1),
    (2, 8, 8, 1),
    (2, 9, 9, 1),
    (2, 10, 10, 1),
    (2, 11, 11, 1),
    (1, 8, 394, 1),
    (7, 9, 230, 1);
-- !TODO more tables, many-to-many and with n same entities