-- creation tables
create table locality_types (
    locality_type_id int generated by default as identity primary key,
    locality_type_name varchar(127)
);
create table locality_trip_descriptions (
    locality_trip_description_id int generated by default as identity primary key,
    description text not null,
    count_of_landmarks int,
    count_of_hotels int,
    year_of_foundation int
);
create table localities (
    locality_id int generated by default as identity primary key,
    locality_name varchar(127) not null unique,
    population int not null,
    area float not null,
    locality_type_id int references locality_types(locality_type_id),
    locality_trip_description_id int references locality_trip_descriptions(locality_trip_description_id)
);
create table road_types (
    road_type_id int generated by default as identity primary key,
    road_type_name varchar(127)
);
create table roads (
    f_locality_id int references localities(locality_id),
    s_locality_id int references localities(locality_id),
    length int not null,
    road_type_id int references road_types(road_type_id)
);
-- fill tables with data
INSERT INTO locality_types(locality_type_name)
VALUES ('City'),
    ('Village');
INSERT INTO locality_trip_descriptions(
        description,
        count_of_landmarks,
        count_of_hotels,
        year_of_foundation
    )
VALUES (
        'Omsk is the third largest city in Siberia after Novosibirsk and Krasnoyarsk, and the twelfth-largest city in Russia. It is an important transport node, serving as a train station for the Trans-Siberian Railway and as a staging post for the Irtysh River.',
        17,
        20,
        1716
    ),
    (
        'Novosibirsk[a] is the largest city and administrative centre of Novosibirsk Oblast and the Siberian Federal District in Russia. As of the 2021 Census, it had a population of 1,633,595, making it the most populous city in Siberia and the third-most populous city in Russia after Moscow and Saint Petersburg. The city is located in southwestern Siberia, on the banks of the Ob River.',
        87,
        94,
        1893
    );
INSERT INTO localities(
        locality_name,
        population,
        area,
        locality_type_id,
        locality_trip_description_id
    )
VALUES ('Omsk', 1181000, 572.5, 1, null),
    ('Sosnovskoe', 3000, 20.7, 2, null),
    ('Kokshetau', 161000, 233.6, 1, null),
    ('Novosibirsk', 1453000, 502.7, 1, null),
    ('Kemerovo', 531000, 294.8, 1, null);
INSERT INTO road_types(road_type_name)
VALUES ('Highway');
INSERT INTO roads(
        f_locality_id,
        s_locality_id,
        length,
        road_type_id
    )
VALUES(1, 4, 639, 1),
    (4, 5, 270, 1);